driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false
    run_options           : "-v <%= File.dirname(__FILE__) %>:/kitchen"

provisioner                 :
  name                      : shell

verifier                    :
  name                      : serverspec
  remote_exec               : false
  default_pattern           : true
  bundler_path              : /opt/hellofresh/kitchen/embedded/bin
  rspec_path                : /opt/hellofresh/kitchen/embedded/bin
  gemfile                   : ./test/integration/Gemfile

platforms                   :
  - name                    : ubuntu-16.04

  - name                    : alpine-3.4
    driver_config           :
     image                  : quay.io/hellofresh/build-alpine:latest
     platform               : alpine
     provision_command:
        - sudo apk add ruby-dev patch

  # - name                    : osx-sierra
  #   driver                  :
  #     name                  : vagrant
  #     box                   : http://files.dryga.com/boxes/osx-sierra-0.3.1.box
  #     network               :
  #                             - ["private_network", {ip: "192.168.56.110"}]
  #     customize             :
  #       cpus                : 2
  #       memory              : 2048
  #     synced_folders        :
  # #                             - ["<%= File.dirname(__FILE__) %>", "/kitchen", "create: true, type: :rsync, group: :staff"]
  #   provisioner             :
  #       script              : build/build.sh

suites                      :
  - name                    : build
    driver_config           :
     image                  : quay.io/hellofresh/kitchen-build-ubuntu:latest
     platform               : ubuntu
    provisioner             :
        script              : build/build.sh

  - name                    : install
    driver_config           :
     image                  : ubuntu:latest
     platform               : ubuntu
    provisioner             :
        script              : build/install.sh
