driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false
    run_options           : "-v <%= File.dirname(__FILE__) %>:/kitchen"

provisioner                 :
  name                      : shell

platforms                   :

  - name                    : ubuntu-16.04
    driver_config           :
     image                  : quay/hellofresh/build-ubuntu:latest
     platform               : ubuntu
    provisioner             :
        script              : build/build.sh

  - name                    : alpine-3.4
    driver_config           :
     image                  : quay/hellofresh/build-alpine:latest
     platform               : alpine
     provision_command:
        - sudo apk add ruby-dev patch
     # ruby-dev
    provisioner             :
        script              : build/build.sh

  - name                    : osx-sierra
    driver                  :
      name                  : vagrant
      box                   : http://files.dryga.com/boxes/osx-sierra-0.3.1.box
      network               :
                              - ["private_network", {ip: "192.168.56.110"}]
      customize             :
        cpus                : 2
        memory              : 2048
      synced_folders        :
                              - ["<%= File.dirname(__FILE__) %>", "/kitchen", "create: true, type: :rsync, group: :staff"]
    provisioner             :
        script              : build/build.sh
suites:
  - name: default

