#!/bin/sh
#
# Perform necessary kitchen removal steps
# after package is uninstalled.
#

## Remove kitchen dir
rm -rf /opt/hellofresh/kitchen

## Clean symlink
rm -f /opt/hellofresh/bin/kitchen
rm -f /opt/hellofresh/bin/kitchen-ansible-inventory


echo "kitchen has been uninstalled!"
exit 0
