#!/bin/sh
#
# Perform necessary kitchen setup steps
# after package is installed.
#
set -e

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}
ln -sf /opt/hellofresh/kitchen/bin/kitchen /opt/hellofresh/bin/kitchen
echo "Thank you for installing kitchen!"

exit 0
