---
# PR.
#  - build for each supported platform
#  - exec binary make sure zero is returned
#  - check plugins
#  - release draft art
#  - try to install packages (
#  - exec binary make sure zero is returned
#  - check plugins

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources  :
  - name   : pr
    type   : pull-request
    source :
      every: true
      repo : hellofresh/hf-kitchen
jobs:
  - name   : PR build Ubuntu
    public : false
    serial : false
    plan   :

      - get                 : pr
        version             : every
        trigger             : True

      - task                : Build Ubuntu PR
        file                : pr/ci/tasks/pr_build_linux.yml
        privileged          : true
        params              :
          INPUT_DIR         : pr
          RUN_ARG           : build-ubuntu

      - task                : Install Ubuntu PR packages
        file                : packages/ci/tasks/pr_install_linux.yml
        privileged          : true
        params              :
          INPUT_DIR         : packages
          RUN_ARG           : install-ubuntu
