---
# PR.
#  - build for each supported platform
#  - exec binary make sure zero is returned
#  - check plugins
#  - release draft art
#  - try to install packages (
#  - exec binary make sure zero is returned
#  - check plugins

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources  :
  - name   : pr
    type   : pull-request
    source :
      every: true
      repo : hellofresh/hf-kitchen
  - name   : release
    type   : github-release
    source :
      user: {{github-user}}
      repository: {{github-repo-name}}
      access_token: {{github-token}}
      drafts: true
  - name: semantic-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.3
      uri: {{github-repo-uri}}
      branch: version
      file: version
      private_key: {{github-private-key}}

jobs:
  - name   : PR build Ubuntu
    public : false
    serial : true
    plan   :

      - get                 : pr
        version             : every
        trigger             : True

      - task                : Build Ubuntu PR
        file                : pr/ci/tasks/pr_build_linux.yml
        privileged          : true
        params              :
          INPUT_DIR         : pr
          RUN_ARG           : build-ubuntu

      - task                : Install Ubuntu PR packages
        file                : packages/ci/tasks/pr_install_linux.yml
        privileged          : true
        params              :
          INPUT_DIR         : packages
          RUN_ARG           : install-ubuntu

      - put                 : semantic-version
        params              :
          bump              : patch

      - put                 : release
        params              :
          name              : semantic-version/version
          tag               : semantic-version/version
          globs             :
          - packages/pkg/*.deb
